title: Team:Harekaze
email: misakiakeno@tomorinao.jp
description: Harekaze is a Japanese Capture The Flag (CTF) team.
url: https://harekaze.com

twitter_username: TeamHarekaze
github_username: TeamHarekaze

markdown: kramdown
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - CNAME
  - README.md
